language: minimal

services:
  - docker

script:
  - docker build --target silverstripe_php -t $TRAVIS_REPO_SLUG:4-php-latest -t $TRAVIS_REPO_SLUG:4-php-7.3 -t $TRAVIS_REPO_SLUG:4.4-php-latest -t $TRAVIS_REPO_SLUG:4.4-php-7.3 .
  - docker build --target silverstripe_nginx -t $TRAVIS_REPO_SLUG:4-nginx-latest -t $TRAVIS_REPO_SLUG:4-nginx-1.17 -t $TRAVIS_REPO_SLUG:4.4-nginx-latest -t $TRAVIS_REPO_SLUG:4.4-nginx-1.17 .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $TRAVIS_REPO_SLUG:4-php-latest
  - docker push $TRAVIS_REPO_SLUG:4-php-7.3
  - docker push $TRAVIS_REPO_SLUG:4.4-php-latest
  - docker push $TRAVIS_REPO_SLUG:4.4-php-7.3
  - docker push $TRAVIS_REPO_SLUG:4-nginx-latest
  - docker push $TRAVIS_REPO_SLUG:4-nginx-1.17
  - docker push $TRAVIS_REPO_SLUG:4.4-nginx-latest
  - docker push $TRAVIS_REPO_SLUG:4.4-nginx-1.17
